import { resolveArchitectureInputSources } from "./command-architecture-inputs-sources.js";
import type { CommandArgs } from "./command-helpers.js";
import {
  getProfile,
  getRootPath,
  loadBoundaryMapIfRequested,
  loadComplexityExportIfRequested,
  loadComplexitySourceConfigIfRequested,
  loadContractBaselineIfRequested,
  loadContractBaselineSourceConfigIfRequested,
  loadDeliveryExportIfRequested,
  loadDeliveryNormalizationProfileIfRequested,
  loadDeliveryObservationsIfRequested,
  loadDeliveryRawObservationsIfRequested,
  loadDeliverySourceConfigIfRequested,
  loadPatternRuntimeNormalizationProfileIfRequested,
  loadPatternRuntimeObservationsIfRequested,
  loadPatternRuntimeRawObservationsIfRequested,
  loadRuntimeObservationsIfRequested,
  loadScenarioCatalogIfRequested,
  loadScenarioObservationSourceConfigIfRequested,
  loadScenarioObservationsIfRequested,
  loadTelemetryExportIfRequested,
  loadTelemetryNormalizationProfileIfRequested,
  loadTelemetryObservationsIfRequested,
  loadTelemetryRawObservationsIfRequested,
  loadTelemetrySourceConfigIfRequested,
  loadTopologyModelIfRequested,
  requireArchitectureConstraints,
} from "./command-helpers.js";
import type { ComputeArchitectureScoresOptions } from "./core/architecture-scoring-types.js";
import type { CommandContext } from "./core/contracts.js";

export async function buildArchitectureScoreOptions(
  args: CommandArgs,
  context: CommandContext,
  policyConfig: ComputeArchitectureScoresOptions["policyConfig"],
): Promise<ComputeArchitectureScoresOptions> {
  const repoPath = getRootPath(args, context);
  const constraints = await requireArchitectureConstraints(args, context);
  const [
    scenarioCatalog,
    scenarioObservations,
    scenarioObservationSourceConfig,
    topologyModel,
    boundaryMap,
    contractBaseline,
    contractBaselineSourceConfig,
    runtimeObservations,
    deliveryObservations,
    deliveryRawObservations,
    deliveryExport,
    deliveryNormalizationProfile,
    deliverySourceConfig,
    telemetryObservations,
    telemetryRawObservations,
    telemetryExport,
    telemetryNormalizationProfile,
    telemetrySourceConfig,
    patternRuntimeObservations,
    patternRuntimeRawObservations,
    patternRuntimeNormalizationProfile,
    complexityExport,
    complexitySourceConfig,
  ] = await Promise.all([
    loadScenarioCatalogIfRequested(args, context),
    loadScenarioObservationsIfRequested(args, context),
    loadScenarioObservationSourceConfigIfRequested(args, context),
    loadTopologyModelIfRequested(args, context),
    loadBoundaryMapIfRequested(args, context),
    loadContractBaselineIfRequested(args, context),
    loadContractBaselineSourceConfigIfRequested(args, context),
    loadRuntimeObservationsIfRequested(args, context),
    loadDeliveryObservationsIfRequested(args, context),
    loadDeliveryRawObservationsIfRequested(args, context),
    loadDeliveryExportIfRequested(args, context),
    loadDeliveryNormalizationProfileIfRequested(args, context),
    loadDeliverySourceConfigIfRequested(args, context),
    loadTelemetryObservationsIfRequested(args, context),
    loadTelemetryRawObservationsIfRequested(args, context),
    loadTelemetryExportIfRequested(args, context),
    loadTelemetryNormalizationProfileIfRequested(args, context),
    loadTelemetrySourceConfigIfRequested(args, context),
    loadPatternRuntimeObservationsIfRequested(args, context),
    loadPatternRuntimeRawObservationsIfRequested(args, context),
    loadPatternRuntimeNormalizationProfileIfRequested(args, context),
    loadComplexityExportIfRequested(args, context),
    loadComplexitySourceConfigIfRequested(args, context),
  ]);
  const {
    contractBaselineSource,
    scenarioObservationSource,
    telemetrySource,
    deliverySource,
    complexitySource,
    additionalProvenance,
  } = await resolveArchitectureInputSources({
    args,
    context,
    scenarioObservations,
    scenarioObservationSourceConfig,
    contractBaseline,
    contractBaselineSourceConfig,
    deliveryObservations,
    deliveryRawObservations,
    deliveryExport,
    deliverySourceConfig,
    telemetryObservations,
    telemetryRawObservations,
    telemetryExport,
    telemetrySourceConfig,
    complexityExport,
    complexitySourceConfig,
  });

  return {
    repoPath,
    constraints,
    policyConfig,
    profileName: getProfile(args),
    ...(scenarioCatalog ? { scenarioCatalog } : {}),
    ...(scenarioObservations ? { scenarioObservations } : {}),
    ...(scenarioObservationSource ? { scenarioObservationSource } : {}),
    ...(topologyModel ? { topologyModel } : {}),
    ...(boundaryMap ? { boundaryMap } : {}),
    ...(contractBaseline ? { contractBaseline } : {}),
    ...(contractBaselineSource ? { contractBaselineSource } : {}),
    ...(runtimeObservations ? { runtimeObservations } : {}),
    ...(deliveryObservations ? { deliveryObservations } : {}),
    ...(deliveryRawObservations ? { deliveryRawObservations } : {}),
    ...(deliveryExport ? { deliveryExport } : {}),
    ...(deliverySource ? { deliverySource } : {}),
    ...(deliveryNormalizationProfile ? { deliveryNormalizationProfile } : {}),
    ...(telemetryObservations ? { telemetryObservations } : {}),
    ...(telemetryRawObservations ? { telemetryRawObservations } : {}),
    ...(telemetryExport ? { telemetryExport } : {}),
    ...(telemetrySource ? { telemetrySource } : {}),
    ...(telemetryNormalizationProfile ? { telemetryNormalizationProfile } : {}),
    ...(patternRuntimeObservations ? { patternRuntimeObservations } : {}),
    ...(patternRuntimeRawObservations ? { patternRuntimeRawObservations } : {}),
    ...(patternRuntimeNormalizationProfile ? { patternRuntimeNormalizationProfile } : {}),
    ...(complexityExport ? { complexityExport } : {}),
    ...(complexitySource ? { complexitySource } : {}),
    additionalProvenance,
    scenarioObservationSourceRequested: Boolean(scenarioObservationSourceConfig),
    telemetrySourceRequested: Boolean(telemetrySourceConfig),
    deliverySourceRequested: Boolean(deliverySourceConfig),
    complexitySourceRequested: Boolean(complexitySourceConfig),
    contractBaselineSourceRequested: Boolean(contractBaselineSourceConfig),
    patternRuntimeRawRequested: Boolean(patternRuntimeRawObservations),
    patternRuntimeNormalizationProfileRequested: Boolean(patternRuntimeNormalizationProfile),
  };
}
